from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(655, 574)
        Dialog.setStyleSheet("background-color: rgb(255, 14, 50);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(40, 60, 551, 80))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.waiterLabel = QtWidgets.QLabel(self.frame)
        self.waiterLabel.setGeometry(QtCore.QRect(110, 20, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.waiterLabel.setFont(font)
        self.waiterLabel.setObjectName("waiterLabel")
        self.detailsLabel = QtWidgets.QLabel(Dialog)
        self.detailsLabel.setGeometry(QtCore.QRect(40, 220, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.detailsLabel.setFont(font)
        self.detailsLabel.setObjectName("detailsLabel")
        self.orderLabel = QtWidgets.QLabel(Dialog)
        self.orderLabel.setGeometry(QtCore.QRect(50, 290, 81, 16))
        self.orderLabel.setObjectName("orderLabel")
        self.totalLabel = QtWidgets.QLabel(Dialog)
        self.totalLabel.setGeometry(QtCore.QRect(460, 290, 101, 16))
        self.totalLabel.setObjectName("totalLabel")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 310, 511, 161))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.transactionsLabel = QtWidgets.QLabel(Dialog)
        self.transactionsLabel.setGeometry(QtCore.QRect(210, 190, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.transactionsLabel.setFont(font)
        self.transactionsLabel.setObjectName("transactionsLabel")
        self.chargeLabel = QtWidgets.QLabel(Dialog)
        self.chargeLabel.setGeometry(QtCore.QRect(140, 290, 91, 16))
        self.chargeLabel.setObjectName("chargeLabel")
        self.serviceChargeLabel = QtWidgets.QLabel(Dialog)
        self.serviceChargeLabel.setGeometry(QtCore.QRect(330, 290, 91, 16))
        self.serviceChargeLabel.setObjectName("serviceChargeLabel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 160, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.driverChargeLabel = QtWidgets.QLabel(Dialog)
        self.driverChargeLabel.setGeometry(QtCore.QRect(240, 290, 81, 20))
        self.driverChargeLabel.setObjectName("driverChargeLabel")
        self.totalOrderLineEdit = QtWidgets.QLineEdit(Dialog)
        self.totalOrderLineEdit.setGeometry(QtCore.QRect(30, 480, 231, 31))
        self.totalOrderLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.totalOrderLineEdit.setObjectName("totalOrderLineEdit")
        self.collectionLineEdit = QtWidgets.QLineEdit(Dialog)
        self.collectionLineEdit.setGeometry(QtCore.QRect(30, 520, 231, 31))
        self.collectionLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.collectionLineEdit.setObjectName("collectionLineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.waiterLabel.setText(_translate("Dialog", "WAITER ON WHEELS"))
        self.detailsLabel.setText(_translate("Dialog", "Details"))
        self.orderLabel.setText(_translate("Dialog", "Order Code"))
        self.totalLabel.setText(_translate("Dialog", "Total"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.transactionsLabel.setText(_translate("Dialog", "Daily Transactions"))
        self.chargeLabel.setText(_translate("Dialog", "Charge"))
        self.serviceChargeLabel.setText(_translate("Dialog", "Service charge"))
        self.driverChargeLabel.setText(_translate("Dialog", "Driver charge"))
        self.totalOrderLineEdit.setPlaceholderText(_translate("Dialog", "Total Order:"))
        self.collectionLineEdit.setPlaceholderText(_translate("Dialog", "Total Collection:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

