from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(620, 550)
        Dialog.setStyleSheet("background-color: rgb(212, 12, 42);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 30, 551, 80))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.waiterLabel = QtWidgets.QLabel(self.frame)
        self.waiterLabel.setGeometry(QtCore.QRect(110, 20, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.waiterLabel.setFont(font)
        self.waiterLabel.setObjectName("waiterLabel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(30, 130, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gpsLabel = QtWidgets.QLabel(Dialog)
        self.gpsLabel.setGeometry(QtCore.QRect(200, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.gpsLabel.setFont(font)
        self.gpsLabel.setObjectName("gpsLabel")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(40, 320, 521, 201))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.detailsLabel = QtWidgets.QLabel(Dialog)
        self.detailsLabel.setGeometry(QtCore.QRect(30, 190, 211, 16))
        self.detailsLabel.setObjectName("detailsLabel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 300, 91, 16))
        self.label.setObjectName("label")
        self.orderLabel = QtWidgets.QLabel(Dialog)
        self.orderLabel.setGeometry(QtCore.QRect(150, 300, 81, 16))
        self.orderLabel.setObjectName("orderLabel")
        self.locationLabel = QtWidgets.QLabel(Dialog)
        self.locationLabel.setGeometry(QtCore.QRect(260, 300, 71, 16))
        self.locationLabel.setObjectName("locationLabel")
        self.vehicleLabel = QtWidgets.QLabel(Dialog)
        self.vehicleLabel.setGeometry(QtCore.QRect(350, 300, 81, 16))
        self.vehicleLabel.setObjectName("vehicleLabel")
        self.phoneLabel = QtWidgets.QLabel(Dialog)
        self.phoneLabel.setGeometry(QtCore.QRect(460, 300, 101, 16))
        self.phoneLabel.setObjectName("phoneLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Driver Location"))
        self.waiterLabel.setText(_translate("Dialog", "WAITER ON WHEELS"))
        self.gpsLabel.setText(_translate("Dialog", "Driver Location [GPS]"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.detailsLabel.setText(_translate("Dialog", "Details"))
        self.label.setText(_translate("Dialog", "Driver Name"))
        self.orderLabel.setText(_translate("Dialog", "Order Code"))
        self.locationLabel.setText(_translate("Dialog", "Location"))
        self.vehicleLabel.setText(_translate("Dialog", "Vehicle No"))
        self.phoneLabel.setText(_translate("Dialog", "Phone Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

