from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(584, 574)
        Dialog.setStyleSheet("background-color: rgb(255, 29, 89);")
        self.codeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.codeLineEdit.setGeometry(QtCore.QRect(20, 300, 221, 31))
        self.codeLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.codeLineEdit.setObjectName("codeLineEdit")
        self.driverLabel = QtWidgets.QLabel(Dialog)
        self.driverLabel.setGeometry(QtCore.QRect(170, 130, 231, 20))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.driverLabel.setFont(font)
        self.driverLabel.setObjectName("driverLabel")
        self.contactLineEdit = QtWidgets.QLineEdit(Dialog)
        self.contactLineEdit.setGeometry(QtCore.QRect(20, 260, 281, 23))
        self.contactLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.contactLineEdit.setObjectName("contactLineEdit")
        self.availabilityLineEdit = QtWidgets.QLineEdit(Dialog)
        self.availabilityLineEdit.setGeometry(QtCore.QRect(20, 340, 221, 31))
        self.availabilityLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.availabilityLineEdit.setText("")
        self.availabilityLineEdit.setObjectName("availabilityLineEdit")
        self.driverNameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.driverNameLineEdit.setGeometry(QtCore.QRect(20, 170, 351, 31))
        self.driverNameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.driverNameLineEdit.setText("")
        self.driverNameLineEdit.setObjectName("driverNameLineEdit")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 10, 551, 80))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.waiterLabel = QtWidgets.QLabel(self.frame)
        self.waiterLabel.setGeometry(QtCore.QRect(110, 20, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.waiterLabel.setFont(font)
        self.waiterLabel.setObjectName("waiterLabel")
        self.reportingLineEdit = QtWidgets.QLineEdit(Dialog)
        self.reportingLineEdit.setGeometry(QtCore.QRect(20, 382, 221, 31))
        self.reportingLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.reportingLineEdit.setObjectName("reportingLineEdit")
        self.vehicleLineEdit = QtWidgets.QLineEdit(Dialog)
        self.vehicleLineEdit.setGeometry(QtCore.QRect(20, 220, 341, 23))
        self.vehicleLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.vehicleLineEdit.setObjectName("vehicleLineEdit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 100, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.orderLineEdit = QtWidgets.QLineEdit(Dialog)
        self.orderLineEdit.setGeometry(QtCore.QRect(20, 430, 221, 31))
        self.orderLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.orderLineEdit.setObjectName("orderLineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Driver Information"))
        self.codeLineEdit.setPlaceholderText(_translate("Dialog", "Order Code:"))
        self.driverLabel.setText(_translate("Dialog", "DRIVER INFORMATION"))
        self.contactLineEdit.setPlaceholderText(_translate("Dialog", "Contact Number:"))
        self.availabilityLineEdit.setPlaceholderText(_translate("Dialog", "Availability"))
        self.driverNameLineEdit.setPlaceholderText(_translate("Dialog", "Driver Name:"))
        self.waiterLabel.setText(_translate("Dialog", "WAITER ON WHEELS"))
        self.reportingLineEdit.setPlaceholderText(_translate("Dialog", "Reporting Time:"))
        self.vehicleLineEdit.setPlaceholderText(_translate("Dialog", "Vehicle Number:"))
        self.orderLineEdit.setPlaceholderText(_translate("Dialog", "Order Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

