from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(604, 563)
        Dialog.setStyleSheet("background-color: rgb(208, 9, 38);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 10, 551, 80))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.waiterLabel = QtWidgets.QLabel(self.frame)
        self.waiterLabel.setGeometry(QtCore.QRect(110, 20, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.waiterLabel.setFont(font)
        self.waiterLabel.setObjectName("waiterLabel")
        self.timeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.timeLineEdit.setGeometry(QtCore.QRect(330, 170, 221, 31))
        self.timeLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.timeLineEdit.setObjectName("timeLineEdit")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(50, 100, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.dateLineEdit = QtWidgets.QLineEdit(Dialog)
        self.dateLineEdit.setGeometry(QtCore.QRect(10, 170, 221, 31))
        self.dateLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateLineEdit.setText("")
        self.dateLineEdit.setObjectName("dateLineEdit")
        self.addressTextEdit = QtWidgets.QTextEdit(Dialog)
        self.addressTextEdit.setGeometry(QtCore.QRect(10, 360, 311, 91))
        self.addressTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addressTextEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addressTextEdit.setObjectName("addressTextEdit")
        self.informationLabel = QtWidgets.QLabel(Dialog)
        self.informationLabel.setGeometry(QtCore.QRect(250, 130, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.informationLabel.setFont(font)
        self.informationLabel.setObjectName("informationLabel")
        self.codeLineEdit = QtWidgets.QLineEdit(Dialog)
        self.codeLineEdit.setGeometry(QtCore.QRect(370, 360, 181, 31))
        self.codeLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.codeLineEdit.setObjectName("codeLineEdit")
        self.customerNameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.customerNameLineEdit.setGeometry(QtCore.QRect(10, 230, 281, 23))
        self.customerNameLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.customerNameLineEdit.setObjectName("customerNameLineEdit")
        self.customerIdLineEdit = QtWidgets.QLineEdit(Dialog)
        self.customerIdLineEdit.setGeometry(QtCore.QRect(10, 270, 281, 23))
        self.customerIdLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.customerIdLineEdit.setObjectName("customerIdLineEdit")
        self.phoneLineEdit = QtWidgets.QLineEdit(Dialog)
        self.phoneLineEdit.setGeometry(QtCore.QRect(10, 310, 281, 23))
        self.phoneLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phoneLineEdit.setObjectName("phoneLineEdit")
        self.detailsLabel = QtWidgets.QLabel(Dialog)
        self.detailsLabel.setGeometry(QtCore.QRect(10, 470, 91, 16))
        self.detailsLabel.setObjectName("detailsLabel")
        self.priceLabel = QtWidgets.QLabel(Dialog)
        self.priceLabel.setGeometry(QtCore.QRect(430, 510, 57, 15))
        self.priceLabel.setObjectName("priceLabel")
        self.itemsLabel = QtWidgets.QLabel(Dialog)
        self.itemsLabel.setGeometry(QtCore.QRect(10, 510, 57, 15))
        self.itemsLabel.setObjectName("itemsLabel")
        self.quantityLabel = QtWidgets.QLabel(Dialog)
        self.quantityLabel.setGeometry(QtCore.QRect(230, 510, 57, 15))
        self.quantityLabel.setObjectName("quantityLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Invoice"))
        self.waiterLabel.setText(_translate("Dialog", "WAITER ON WHEELS"))
        self.timeLineEdit.setPlaceholderText(_translate("Dialog", "Time"))
        self.dateLineEdit.setPlaceholderText(_translate("Dialog", "Date"))
        self.addressTextEdit.setPlaceholderText(_translate("Dialog", "Customer Address:"))
        self.informationLabel.setText(_translate("Dialog", "INVOICE"))
        self.codeLineEdit.setPlaceholderText(_translate("Dialog", "Order Code:"))
        self.customerNameLineEdit.setPlaceholderText(_translate("Dialog", "Customer Name"))
        self.customerIdLineEdit.setPlaceholderText(_translate("Dialog", "Customer ID"))
        self.phoneLineEdit.setPlaceholderText(_translate("Dialog", "Customer Phone"))
        self.detailsLabel.setText(_translate("Dialog", "Order Details"))
        self.priceLabel.setText(_translate("Dialog", "Price"))
        self.itemsLabel.setText(_translate("Dialog", "Items"))
        self.quantityLabel.setText(_translate("Dialog", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

