from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(581, 579)
        Dialog.setStyleSheet("background-color: rgb(255, 7, 52);")
        self.orderLabel = QtWidgets.QLabel(Dialog)
        self.orderLabel.setGeometry(QtCore.QRect(30, 230, 81, 16))
        self.orderLabel.setObjectName("orderLabel")
        self.totalOrderLineEdit = QtWidgets.QLineEdit(Dialog)
        self.totalOrderLineEdit.setGeometry(QtCore.QRect(20, 430, 231, 31))
        self.totalOrderLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.totalOrderLineEdit.setObjectName("totalOrderLineEdit")
        self.collectionLineEdit = QtWidgets.QLineEdit(Dialog)
        self.collectionLineEdit.setGeometry(QtCore.QRect(20, 470, 231, 31))
        self.collectionLineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.collectionLineEdit.setObjectName("collectionLineEdit")
        self.totalLabel = QtWidgets.QLabel(Dialog)
        self.totalLabel.setGeometry(QtCore.QRect(440, 230, 101, 16))
        self.totalLabel.setObjectName("totalLabel")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 551, 80))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.waiterLabel = QtWidgets.QLabel(self.frame)
        self.waiterLabel.setGeometry(QtCore.QRect(110, 20, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.waiterLabel.setFont(font)
        self.waiterLabel.setObjectName("waiterLabel")
        self.detailsLabel = QtWidgets.QLabel(Dialog)
        self.detailsLabel.setGeometry(QtCore.QRect(10, 170, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.detailsLabel.setFont(font)
        self.detailsLabel.setObjectName("detailsLabel")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 250, 511, 161))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.transactionsLabel = QtWidgets.QLabel(Dialog)
        self.transactionsLabel.setGeometry(QtCore.QRect(180, 140, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.transactionsLabel.setFont(font)
        self.transactionsLabel.setObjectName("transactionsLabel")
        self.collectionLabel = QtWidgets.QLabel(Dialog)
        self.collectionLabel.setGeometry(QtCore.QRect(120, 230, 91, 16))
        self.collectionLabel.setObjectName("collectionLabel")
        self.serviceChargeLabel = QtWidgets.QLabel(Dialog)
        self.serviceChargeLabel.setGeometry(QtCore.QRect(320, 230, 101, 16))
        self.serviceChargeLabel.setObjectName("serviceChargeLabel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 110, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.driverChargeLabel = QtWidgets.QLabel(Dialog)
        self.driverChargeLabel.setGeometry(QtCore.QRect(220, 230, 91, 20))
        self.driverChargeLabel.setObjectName("driverChargeLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.orderLabel.setText(_translate("Dialog", "Total Orders"))
        self.totalOrderLineEdit.setPlaceholderText(_translate("Dialog", "Total Orders:"))
        self.collectionLineEdit.setPlaceholderText(_translate("Dialog", "Total Collection:(inclusive all)"))
        self.totalLabel.setText(_translate("Dialog", "Total"))
        self.waiterLabel.setText(_translate("Dialog", "WAITER ON WHEELS"))
        self.detailsLabel.setText(_translate("Dialog", "Details"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.transactionsLabel.setText(_translate("Dialog", "Weekly Transactions"))
        self.collectionLabel.setText(_translate("Dialog", "Collection"))
        self.serviceChargeLabel.setText(_translate("Dialog", "Service charges"))
        self.driverChargeLabel.setText(_translate("Dialog", "Driver charges"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

